// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmqnjokcddotmhwhjuqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtcW5qb2tjZGRvdG1od2hqdXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NTAyOTAsImV4cCI6MjA0OTQyNjI5MH0.t5jodBGwOEmijxO8e6Oofd6fuTHRLHjm8E7gjbiq4WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);